backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Header",
              name: "Header",
              widget: object,
              fields:
                [
                  { label: "First Name", name: "logotext1", widget: string },
                  { label: "Last Name", name: "logotext2", widget: string },
                ],
            }
          - {
              label: "Menus",
              name: "topmenu",
              widget: list,
              fields:
                [
                  { label: "URL", name: "menueurl", widget: string },
                  { label: "Name", name: "menuename", widget: string },
                ],
            }
          - {
              label: "Intro",
              name: "intro",
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Subtitle", name: "subtitle", widget: string },
                  {
                    label: "Description",
                    name: "homedescription",
                    widget: text,
                  },
                ],
            }
          - {
              label: "Intro Image",
              name: "introImage",
              widget: object,
              fields: [{ label: "Image", name: "introimage", widget: image }],
            }
          - {
              label: "Button",
              name: "button",
              widget: object,
              fields:
                [
                  {
                    label: "Button Image Class",
                    name: "butnImg",
                    widget: string,
                  },
                  { label: "Button Text", name: "btnText", widget: "string" },
                  { label: "Button URL", name: "butnUrl", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "sociallinks",
              widget: list,
              fields:
                [
                  {
                    label: "Scocial Media Icon",
                    name: "soicon",
                    widget: "string",
                  },
                  { label: "URL", name: ".URL", widget: "string" },
                ],
            }
          - {
              label: "Who am I?",
              name: blurb,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  {
                    label: "Profile Picture",
                    name: "aboutimage",
                    widget: image,
                  },
                  { label: "Text", name: "abouttext", widget: "text" },
                ],
            }
          - {
              label: "About me Button",
              name: "aboutbutton",
              widget: object,
              fields:
                [
                  {
                    label: "Button Image Class",
                    name: "abouticon",
                    widget: string,
                  },
                  {
                    label: "Button Text",
                    name: "aboutbtnText",
                    widget: "string",
                  },
                  {
                    label: "Button URL",
                    name: "aboutbuttonURL",
                    widget: "string",
                  },
                ],
            }
          - {
              label: "Education Intro",
              name: "educationintro",
              widget: object,
              fields:
                [
                  {
                    label: "Heading",
                    name: "educationheading",
                    widget: string,
                  },
                  { label: "Text", name: "educationtext", widget: "text" },
                ],
            }
          - {
              label: "Education",
              name: "education",
              widget: list,
              fields:
                [
                  { label: "Year", name: "year", widget: string },
                  { label: "School", name: "school", widget: string },
                  { label: "Degree", name: "degree", widget: "text" },
                ],
            }
          - {
              label: "Experience",
              name: "experience",
              widget: list,
              fields:
                [
                  { label: "Work Year", name: "workyear", widget: string },
                  { label: "Work Role", name: "workrole", widget: string },
                  { label: "Company", name: "company", widget: "text" },
                ],
            }
          - {
              label: "Experience Ttitle",
              name: "experiencetitle",
              widget: string,
            }
          - {
              label: "Experience Description",
              name: "experiencedescription",
              widget: text,
            }
          - {
              label: "Experience Button Linkedin URL",
              name: "experiencebuttonURL",
              widget: string,
            }
          - {
              label: "Experience Button Icon",
              name: "experiencebuttonicon",
              widget: string,
            }
          - {
              label: "Experience button Txt",
              name: "experiencebtnText",
              widget: string,
            }
          - {
              label: "Experience Resume URL",
              name: "experiencebutton2URL",
              widget: string,
            }
          - {
              label: "Experience Resume Button Icon",
              name: "experiencebutton2icon",
              widget: string,
            }
          - {
              label: "Experience Resume Button TXT",
              name: "experiencebutton2btnText",
              widget: string,
            }
          - {
              label: "Certificate Intro",
              name: "certificateintro",
              widget: object,
              fields:
                [
                  {
                    label: "Certificate Heading",
                    name: "certificateheading",
                    widget: string,
                  },
                  {
                    label: "Certificate Text",
                    name: "certificatetext",
                    widget: "text",
                  },
                ],
            }
          - {
              label: "Certificate",
              name: "certificate",
              widget: list,
              fields:
                [
                  { label: "Year", name: "year", widget: string },
                  { label: "Certificate", name: "certificate", widget: string },
                  { label: "Location", name: "location", widget: "text" },
                ],
            }
          - {
              label: "Publications Intro",
              name: "publicationsintro",
              widget: object,
              fields:
                [
                  {
                    label: "Publications Ttitle",
                    name: "publicationstitle",
                    widget: string,
                  },
                  {
                    label: "Publications Description",
                    name: "publicationsdescription",
                    widget: text,
                  },
                  {
                    label: "Publications Button Linkedin URL",
                    name: "publicationsbuttonURL",
                    widget: string,
                  },
                  {
                    label: "Publications Button Icon",
                    name: "publicationsbuttonicon",
                    widget: string,
                  },
                  {
                    label: "Publications button Txt",
                    name: "publicationsbtnText",
                    widget: string,
                  },
                  {
                    label: "Publications Resume URL",
                    name: "publicationsbutton2URL",
                    widget: string,
                  },
                  {
                    label: "Publications Resume Button Icon",
                    name: "publicationsbutton2icon",
                    widget: string,
                  },
                  {
                    label: "Publications Resume Button TXT",
                    name: "publicationsbutton2btnText",
                    widget: string,
                  },
                ],
            }
          - {
              label: "Publications",
              name: "publications",
              widget: list,
              fields:
                [
                  {
                    label: "Publication Year",
                    name: "publishyear",
                    widget: string,
                  },
                  {
                    label: "Publication Location",
                    name: "publishLocation",
                    widget: text,
                  },
                  {
                    label: "Publication Title",
                    name: "publishtitle",
                    widget: "string",
                  },
                ],
            }
          - {
              label: "Client Title",
              name: "client_and_work_title",
              widget: string,
            }
          - {
              label: "Application and Tools",
              name: "applications",
              widget: list,
              fields:
                [
                  { label: "Tool Logo", name: "toolimg", widget: image },
                  {
                    label: "Tool Logo TXT",
                    name: "toolaltimg",
                    widget: string,
                  },
                ],
            }
          - {
              label: "Clients & Works",
              name: "clientwork",
              widget: list,
              fields:
                [
                  {
                    label: "Project Title",
                    name: "projecttitle",
                    widget: string,
                  },
                  {
                    label: "Project Description",
                    name: "projectdescription",
                    widget: text,
                  },
                  { label: "Project Image", name: "workimage", widget: image },
                  {
                    label: "Project Image Text",
                    name: "workimgtitle",
                    widget: string,
                  },
                  { label: "Button Icon", name: "workicon", widget: string },
                  { label: "Button TXT", name: "workbtnText", widget: string },
                  { label: "Button URL", name: "workbtnURL", widget: string },
                  { label: "Left", name: "is_even", widget: "string" },
                ],
            }
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - label: Values
            name: values
            widget: list
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Image, name: imageUrl, widget: image }
